version: '2.2'

volumes:
  # Set this to your local media directory
  media:
    driver: local
    driver_opts:
      device: ~/Music
      type: none
      o: bind

  # Forward local pulseaudio state directory so it can be imported.
  # Alternatively, you may specify the PULSE_COOKIE_DATA environment variable
  pulse:
    driver: local
    driver_opts:
      device: ~/.config/pulse
      type: none
      o: bind

  config:
  data:
  cache:

networks:
  host:
    external: true

services:
  mopidy:
    build:
      context: .

    hostname: mopidy
    container_name: mopidy

    userns_mode: host
    networks:
      - host

    expose:
      - 6600
      - 6680
      - 6681

    volumes:
      - .:/app
      - config:/config
      - data:/data
      - cache:/cache
      - pulse:/pulse:ro
      - media:/media:ro

    environment:
      - PULSE_SERVER
      - PULSE_COOKIE_DATA

      - DEBUG=1
      - VERBOSE=1
